const ssbuRoster = new Set(
    [
    "BANJO & KAZOOIE",
    "BAYONETTA",
    "BOWSER",
    "BOWSER JR.",
    "BYLETH",
    "CAPTAIN FALCON",
    "CHROM",
    "CLOUD",
    "CORRIN",
    "DAISY",
    "DARK PIT",
    "DARK SAMUS",
    "DIDDY KONG",
    "DONKEY KONG",
    "DR. MARIO",
    "DUCK HUNT",
    "FALCO",
    "FOX",
    "GANONDORF",
    "GRENINJA",
    "HERO",
    "THE ICE CLIMBERS",
    "IKE",
    "INCINEROAR",
    "INKLING",
    "ISABELLE",
    "JIGGLYPUFF",
    "JOKER",
    "KAZUYA",
    "KEN",
    "KING DEDEDE",
    "KING K. ROOL",
    "KIRBY",
    "LINK",
    "LITTLE MAC",
    "LUCARIO",
    "LUCAS",
    "LUCINA",
    "LUIGI",
    "MARIO",
    "MARTH",
    "MEGA MAN",
    "META KNIGHT",
    "MEWTWO",
    "MII BRAWLER",
    "MII GUNNER",
    "MII FIGHTER",
    "MIN MIN",
    "MR. GAME & WATCH",
    "NESS",
    "CAPTAIN OLIMAR",
    "PAC-MAN",
    "PALUTENA",
    "PEACH",
    "PICHU",
    "PIKACHU",
    "PIRANHA PLANT",
    "PIT",
    "POKEMON TRAINER",
    "PYRA/MYTHRA",
    "R.O.B. THE ROBOT",
    "ROBIN",
    "ROSALINA",
    "ROY",
    "RICHTER",
    "RIDLEY",
    "RYU",
    "SAMUS",
    "SEPHIROTH",
    "SHEIK",
    "SHULK",
    "SIMON BELMONT",
    "SOLID SNAKE",
    "SONIC",
    "SORA",
    "STEVE",
    "TERRY",
    "TOON LINK",
    "VILLAGER",
    "WARIO",
    "WII FIT TRAINER",
    "WOLF",
    "YOSHI",
    "YOUNG LINK",
    "ZELDA",
    "ZERO SUIT SAMUS"
    ]

);

module.exports = {ssbuRoster};



